name: Application deployment on AWS

on:
  workflow_call:
    

jobs:
  working-job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Message
        run: echo "Application deployed on AWS successfully ➡️"